export const lostLands2026 = {
  id: 'lost-lands-2026',
  name: 'Lost Lands 2026',
  shortName: 'Lost Lands',
  country: null,
  city: null,
  region: null,
  venue: null,
  timezone: null,
  startDate: null,
  endDate: null,
  status: null,
  description: null,
  logo: null,
  heroImage: null,
  mapImage: null,
  theme: null,
  stages: [],
  artists: [],
  discoveryIds: [],
  missionIds: [],
  rewardIds: [],
  liveDropIds: [],
  gpsDropIds: [],
}
