import { lostLands2026Discoveries } from './lostLands2026Discoveries.js'

export const lostLands2026 = {
  id: 'lost-lands-2026',
  festivalBrandId: 'lost-lands',
  year: 2026,
  name: 'Lost Lands 2026',
  displayName: 'Lost Lands 2026',
  shortName: 'Lost Lands',
  country: 'United States',
  city: 'Thornville',
  region: 'Ohio',
  venue: 'Legend Valley',
  timezone: 'America/New_York',
  startDate: '2026-09-18',
  endDate: '2026-09-20',
  status: 'upcoming',
  description:
    'A prehistoric-themed bass festival experience at Legend Valley.',
  logo: null,
  heroImage: null,
  mapImage: null,
  theme: {
    name: null,
    tagline: null,
    description: null,
    palette: [],
    artworkDirection: null,
    typographyDirection: null,
    effects: [],
  },
  stages: [
    {
      id: 'lost-lands-prehistoric-stage',
      name: 'The Prehistoric Stage',
      discoveryId: 'lost-lands-prehistoric-stage',
    },
    {
      id: 'lost-lands-crater',
      name: 'The Crater',
      discoveryId: 'lost-lands-crater',
    },
  ],
  artists: [],
  discoveryIds: lostLands2026Discoveries.map((discovery) => discovery.id),
  missionIds: [],
  rewardIds: [],
  liveDropIds: [],
  gpsDropIds: [],
}
